### ISSUE TITLE
How do you use them?

### ISSUE THREAD

**Issue by onel** [patrickkettner/WebWorkerPreProcessor#3]
Hi Patrick, great idea for the project. But ... stupid question, how do you use it? 
Let's say the less transpiler.

**Comment by patrickkettner** [comment]
Hey @onel!

Its sort of intentionally undocumented right now while I optimizer the build. BUT, happy to explain some. Which transpiler do you want to use?

**Comment by onel** [comment]
Hey, I am interested in the less transpiler. Have you seen any
improvements/benefits by using it inside a sw?

**Comment by patrickkettner** [comment]
So it is not a service worker, though it could certainly be used inside of one. It is a webworker.  I don't use less in a production case, so I don't have benchmarks to go against. If you are compiling it on the fly currently, than doing it in a worker would almost always be more performant as it wouldnt block for compilations cycles.

As far as usage goes, grab the version of the library that you want to use (I try to publish as many older versions as possible for folks who arent able to upgrade). In this case, [2.7.1](https://github.com/patrickkettner/WebWorkerPreProcessor/blob/master/dist/less-v2.7.1.min.js) is the latest less version. 

It is packaged as a worker already, so you would want to have something like the following code on your site (or other script included on your site).

```js
let less = new Worker('./less-v2.7.1.min.js')

lessBuilder = function(str, opts, cb) {
  less.onmessage = function(e) {
    cb(JSON.parse(e.data));
  };

  less.postMessage(JSON.stringify({
    css: str,
    options: opts
  }));
};
```

From there, you call `lessBuilder` with three arguments. The first being a string representing the less but you want to have compiled. The second being a less configuration object, and finally a callback function for the result object. The result will be an object with a `css` value for the compiled values, and a `error` value for any compilation errors. 

Few things to keep in mind.

1. This is in no way a replacement for precompilation. Precompiling all of your assets will always be faster, since you can't beat work done ahead of time. However if you are prototyping or running a service that has transpilation as a part of it, than it would work great for you.
2. this is the node version of less, not the browser version of less. There should not be any difference between the two, but on the off chance that there is, its worth knowing. I plan on adding a compiled browser version of less in the future, but its lower priority at the moment.

hope that helps!

**Comment by onel** [comment]
Ohhh, nice. I have no idea why I thought about service workers, the hint was in the title.
Thanks a lot for the explanation, this is interesting.
